// swift-tools-version: 6.0
//
// LicenseKit 1.0.0 — binary distribution (Tier 2).
//
// Generated by Scripts/licensekit-dist; do not edit by hand.
//
// Every product here is a prebuilt XCFramework. The API is identical to the
// source distribution, with one caveat: this build enables library evolution,
// so a switch over a non-frozen public enum needs an `@unknown default`.
// See docs/distribution.md.
import PackageDescription

let package = Package(
    name: "LicenseKit",
    platforms: [
        .iOS(.v15),
        .macOS(.v12),
        .tvOS(.v15),
        .watchOS(.v8),
        .visionOS(.v1),
    ],
    products: [
        // One product, so a consumer adds a single dependency and gets the
        // umbrella module plus everything it re-exports.
        .library(name: "LicenseKit", targets: [
            "LicenseKit",
            "LicenseKitCore",
            "LicenseKitCrypto",
            "LicenseKitFormats",
            "LicenseKitProviders",
            "LicenseKitStorage",
        ]),

        // Vendor-side issuing tools, macOS only. Deliberately a separate product:
        // linking this into a shipping client app hands out the type that signs
        // licenses. Depend on it from your issuing tool, never from your app.
        .library(name: "LicenseKitVendor", targets: ["LicenseKitVendor"]),
    ],
    targets: [
        .binaryTarget(
            name: "LicenseKit",
            url: "https://github.com/gumbracelet/LicenseKit-SDK/releases/download/1.0.0/LicenseKit.xcframework.zip",
            checksum: "b507c8ad219afcf874609d6c258dc1b83bbd834d851e164bc78badd6ab25b27c"
        ),
        .binaryTarget(
            name: "LicenseKitCore",
            url: "https://github.com/gumbracelet/LicenseKit-SDK/releases/download/1.0.0/LicenseKitCore.xcframework.zip",
            checksum: "d3d05197f4216c8535975237c660b6d9a38682cb1a5bac092e4c2e8e119b5ad7"
        ),
        .binaryTarget(
            name: "LicenseKitCrypto",
            url: "https://github.com/gumbracelet/LicenseKit-SDK/releases/download/1.0.0/LicenseKitCrypto.xcframework.zip",
            checksum: "63d6b5b3dc30ddd921aadf05b48aa331f2778658ff901ce15551a743ae370329"
        ),
        .binaryTarget(
            name: "LicenseKitFormats",
            url: "https://github.com/gumbracelet/LicenseKit-SDK/releases/download/1.0.0/LicenseKitFormats.xcframework.zip",
            checksum: "64fbde3f4835dfeead79f4d268e37ef04d2f37067206ff66251eec477f8d67ae"
        ),
        .binaryTarget(
            name: "LicenseKitProviders",
            url: "https://github.com/gumbracelet/LicenseKit-SDK/releases/download/1.0.0/LicenseKitProviders.xcframework.zip",
            checksum: "c48352ba37ae330ee1510c10880a1dfed1e08daf0bcbcc3d40aa8ff0ea6ccde4"
        ),
        .binaryTarget(
            name: "LicenseKitStorage",
            url: "https://github.com/gumbracelet/LicenseKit-SDK/releases/download/1.0.0/LicenseKitStorage.xcframework.zip",
            checksum: "404dfe91f1570f40a00db92a59efc5994ef90d3f0b9e2de64c6db159cca538e8"
        ),
        .binaryTarget(
            name: "LicenseKitVendor",
            url: "https://github.com/gumbracelet/LicenseKit-SDK/releases/download/1.0.0/LicenseKitVendor.xcframework.zip",
            checksum: "ff5765924d8e073289cf56f38f625b8337a676d8f281935bcf6c2fda5caef0bb"
        ),
    ]
)
