// swift-tools-version: 6.0
//
// LicenseKit 1.0.1 — binary distribution (Tier 2).
//
// Generated by Scripts/licensekit-dist; do not edit by hand.
//
// Every product here is a prebuilt XCFramework. The API is identical to the
// source distribution, with one caveat: this build enables library evolution,
// so a switch over a non-frozen public enum needs an `@unknown default`.
// See docs/distribution.md.
import PackageDescription

let package = Package(
    name: "LicenseKit",
    platforms: [
        .iOS(.v15),
        .macOS(.v12),
        .tvOS(.v15),
        .watchOS(.v8),
        .visionOS(.v1),
    ],
    products: [
        // One product, so a consumer adds a single dependency and gets the
        // umbrella module plus everything it re-exports.
        .library(name: "LicenseKit", targets: [
            "LicenseKit",
            "LicenseKitCore",
            "LicenseKitCrypto",
            "LicenseKitFormats",
            "LicenseKitProviders",
            "LicenseKitStorage",
        ]),

        // Vendor-side issuing tools, macOS only. Deliberately a separate product:
        // linking this into a shipping client app hands out the type that signs
        // licenses. Depend on it from your issuing tool, never from your app.
        //
        // It carries the client targets too, because each XCFramework holds only
        // its own object code: the issuing tools' references to Core, Crypto and
        // Formats are undefined until those archives are on the link line. The
        // whole client list is named rather than just the three it needs, so this
        // never drifts from Package.swift's dependency graph. That widens which
        // modules a vendor tool may import; it does not widen what a client app
        // gets, which is the direction that matters.
        .library(name: "LicenseKitVendor", targets: [
            "LicenseKitVendor",
            "LicenseKit",
            "LicenseKitCore",
            "LicenseKitCrypto",
            "LicenseKitFormats",
            "LicenseKitProviders",
            "LicenseKitStorage",
        ]),
    ],
    targets: [
        .binaryTarget(
            name: "LicenseKit",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.0.1/LicenseKit.xcframework.zip",
            checksum: "b43081c4f4f6eae505ac2a729312c2a0c9266bb0c73af3489003a44b4fd40738"
        ),
        .binaryTarget(
            name: "LicenseKitCore",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.0.1/LicenseKitCore.xcframework.zip",
            checksum: "3f4abe32843483c522d9f1774a87c2cc9322fb58585e91929a2708320127262c"
        ),
        .binaryTarget(
            name: "LicenseKitCrypto",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.0.1/LicenseKitCrypto.xcframework.zip",
            checksum: "0083434118832070a4fb880ddd5b85d4cb8921b04106e16017a66f64fed48879"
        ),
        .binaryTarget(
            name: "LicenseKitFormats",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.0.1/LicenseKitFormats.xcframework.zip",
            checksum: "0c49aec350778d7db182659172f2695bc51303d644af199265dc08d316557c73"
        ),
        .binaryTarget(
            name: "LicenseKitProviders",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.0.1/LicenseKitProviders.xcframework.zip",
            checksum: "503b72b79bab0dde277ed33672c0b26d164c1eb5036f1b02f4583c467c5ce3a9"
        ),
        .binaryTarget(
            name: "LicenseKitStorage",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.0.1/LicenseKitStorage.xcframework.zip",
            checksum: "f674a32df91c1ca1d42f97acd2d068d9e4ff5dc7f44e3004a8d5aafc40299816"
        ),
        .binaryTarget(
            name: "LicenseKitVendor",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.0.1/LicenseKitVendor.xcframework.zip",
            checksum: "a1905bc8021427d3a25c40906c90ca8dfcecc18bdf7aeeb2d36a08f3afb0f5da"
        ),
    ]
)
