// swift-tools-version: 6.0
//
// LicenseKit 1.1.0 — binary distribution (Tier 2).
//
// Generated by Scripts/licensekit-dist; do not edit by hand.
//
// Every product here is a prebuilt XCFramework. The API is identical to the
// source distribution, with one caveat: this build enables library evolution,
// so a switch over a non-frozen public enum needs an `@unknown default`.
// See docs/distribution.md.
import PackageDescription

let package = Package(
    name: "LicenseKit",
    platforms: [
        .iOS(.v15),
        .macOS(.v12),
        .tvOS(.v15),
        .watchOS(.v8),
        .visionOS(.v1),
    ],
    products: [
        // One product, so a consumer adds a single dependency and gets the
        // umbrella module plus everything it re-exports.
        .library(name: "LicenseKit", targets: [
            "LicenseKit",
            "LicenseKitCore",
            "LicenseKitCrypto",
            "LicenseKitFormats",
            "LicenseKitProviders",
            "LicenseKitStorage",
        ]),

        // Vendor-side issuing tools, macOS only. Deliberately a separate product:
        // linking this into a shipping client app hands out the type that signs
        // licenses. Depend on it from your issuing tool, never from your app.
        //
        // It carries the client targets too, because each XCFramework holds only
        // its own object code: the issuing tools' references to Core, Crypto and
        // Formats are undefined until those archives are on the link line. The
        // whole client list is named rather than just the three it needs, so this
        // never drifts from Package.swift's dependency graph. That widens which
        // modules a vendor tool may import; it does not widen what a client app
        // gets, which is the direction that matters.
        .library(name: "LicenseKitVendor", targets: [
            "LicenseKitVendor",
            "LicenseKit",
            "LicenseKitCore",
            "LicenseKitCrypto",
            "LicenseKitFormats",
            "LicenseKitProviders",
            "LicenseKitStorage",
        ]),
    ],
    targets: [
        .binaryTarget(
            name: "LicenseKit",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.1.0/LicenseKit.xcframework.zip",
            checksum: "3e52483645190dab70afba8221c83d42590abbdabd24d1e952a5dc3049055d9f"
        ),
        .binaryTarget(
            name: "LicenseKitCore",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.1.0/LicenseKitCore.xcframework.zip",
            checksum: "54ab4fb5107dfc424c6192ac44f0de9ef81b2b3ec9e08f7a5974e17af3bfa69a"
        ),
        .binaryTarget(
            name: "LicenseKitCrypto",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.1.0/LicenseKitCrypto.xcframework.zip",
            checksum: "4854103ea2573fb987de5b1020a189b6c5f605fc7a1015aed53eb33e9a510357"
        ),
        .binaryTarget(
            name: "LicenseKitFormats",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.1.0/LicenseKitFormats.xcframework.zip",
            checksum: "16807520e56adb319280f23af0b88067285711315b6419fbf5d24a989ee18c95"
        ),
        .binaryTarget(
            name: "LicenseKitProviders",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.1.0/LicenseKitProviders.xcframework.zip",
            checksum: "e6ef61ed3957897fe527079f80d97fc78e6ebe1faddd8a92473953d90a443661"
        ),
        .binaryTarget(
            name: "LicenseKitStorage",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.1.0/LicenseKitStorage.xcframework.zip",
            checksum: "594a1e9586c86e126a6b1d977d465d7be52118a479d4c44c3f046fbbc6fe4c90"
        ),
        .binaryTarget(
            name: "LicenseKitVendor",
            url: "https://github.com/atcharm/LicenseKit-SDK/releases/download/1.1.0/LicenseKitVendor.xcframework.zip",
            checksum: "9e01fabda61f795f6f50f40cad27b4d10711f2cc7c95cae282e7170d401acd53"
        ),
    ]
)
